AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  f-app
  Sample SAM Template for f-app

Globals:
  Function:
    Timeout: 3

Resources:

  OrderApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowHeaders: "'*'"
        AllowMethods: "'*'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

  OrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs12.x
      Timeout: 25
      MemorySize: 1024
      Events:
        Order:
          Type: Api
          Properties:
            Path: /order
            Method: POST
            RestApiId: !Ref OrderApi

Outputs:
  OrderApiEndPoint:
    Description: "Order API End Point"
    Value: !GetAtt OrderFunction.Arn

